import "./globals.css";
import type { Metadata } from "next";
import { FontMulish } from "@/styles/fonts";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${FontMulish.variable}`}>
      {/* <script
        type="module"
        src="https://public.tableau.com/javascripts/api/tableau.embedding.3.latest.js"
        async
      ></script> */}
      <body>{children}</body>
    </html>
  );
}
